//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class AdminDirectoryService, NSObject, NSString;

@interface ADMDSNode : NSObject
{
    unsigned int mNodeReference;
    NSString *mNodeName;
    AdminDirectoryService *mDirectoryService;
    NSObject<OS_dispatch_semaphore> *mOpenCloseSemaphore;
}

+ (void)closeDefaultLocalNode;
+ (BOOL)isConnectedToNetwork;
+ (BOOL)nodeIsDefaultLocalNode:(unsigned int)arg1;
+ (id)nodeWithName:(id)arg1;
+ (id)openDefaultLocalNode;
+ (id)openProxyNodeAtAddress:(id)arg1 name:(id)arg2 password:(id)arg3 port:(long long)arg4;
+ (id)openSearchNode;
//- (int)_authenticateNodeWithName:(id)arg1 password:(id)arg2 oldPassword:(id)arg3 data:(id)arg4 method:(const char *)arg5 doAuthentication:(BOOL)arg6;
//- (id)_findRecordsByID:(long long)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_7d936526 *)arg3 expectedCount:(unsigned int)arg4;
//- (id)_findRecordsWithName:(CDStruct_166d2db6 *)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_166d2db6 *)arg3 expectedCount:(unsigned int)arg4;
//- (id)_findUsersWithFullName:(CDStruct_7d936526 *)arg1 attribute:(CDStruct_166d2db6 *)arg2 expectedCount:(unsigned int)arg3;
//- (id)_recordsFromBuffer:(CDStruct_7d936526 *)arg1 count:(unsigned int)arg2;
- (int)authenticateName:(id)arg1 withPassword:(id)arg2;
- (int)authenticateNodeWithAuthorization:(id)arg1;
- (void)close;
- (void)dealloc;
- (void)deauthenticate;
- (unsigned int)dirNodeReference;
- (id)directoryService;
- (void)finalize;
//- (id)findRecordByID:(long long)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_7d936526 *)arg3;
//- (id)findRecordWithName:(CDStruct_166d2db6 *)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_166d2db6 *)arg3;
//- (id)findRecordsByID:(long long)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_7d936526 *)arg3;
//- (id)findRecordsWithName:(CDStruct_166d2db6 *)arg1 type:(CDStruct_166d2db6 *)arg2 attribute:(CDStruct_166d2db6 *)arg3;
//- (id)findUserWithFullName:(CDStruct_7d936526 *)arg1 attribute:(CDStruct_166d2db6 *)arg2;
//- (id)findUsersWithFullName:(CDStruct_7d936526 *)arg1 attribute:(CDStruct_166d2db6 *)arg2;
- (id)hashedPasswordForUser:(id)arg1;
- (id)initWithNodeName:(id)arg1;
- (BOOL)isNetInfoNode;
- (BOOL)isOpen;
- (id)nodeName;
- (BOOL)open;
- (void)setDirectoryService:(id)arg1;
- (BOOL)setHashedPassword:(id)arg1 forUser:(id)arg2;
- (long long)setPassword:(id)arg1 oldPassword:(id)arg2 forUser:(id)arg3;
- (long long)setPasswordAsRoot:(id)arg1 forUser:(id)arg2;
- (BOOL)setPasswordScheme:(const char *)arg1 forUser:(id)arg2 password:(id)arg3;
- (int)verifyUserName:(id)arg1 password:(id)arg2;

@end

