//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class ADMDSNode, NSString;

@interface ADMDSRecord : NSObject
{
    unsigned int mRecordReference;
    NSString *mRecordName;
    NSString *mRecordType;
    ADMDSNode *mNode;
}

+ (long long)nextFreeIDInRange:(struct _NSRange)arg1;
- (void)_cleanUpDeletedRecord;
- (BOOL)_setValue:(id)arg1 forKey:(id)arg2;
- (BOOL)addAttribute:(id)arg1 value:(id)arg2;
- (BOOL)addValue:(id)arg1 toAttributeType:(id)arg2;
- (id)attributeForType:(id)arg1 fullInfo:(BOOL)arg2;
- (id)attributesForTypes:(id)arg1;
- (void)close;
- (BOOL)createRecord;
- (BOOL)createRecordInNode:(id)arg1 withAttributes:(id)arg2;
- (BOOL)createRecordWithAttributes:(id)arg1;
- (void)dealloc;
- (BOOL)deleteRecord;
- (id)description;
- (void)finalize;
- (id)generatedUID;
- (id)initWithRecord:(id)arg1;
- (id)initWithRecordName:(const char *)arg1 type:(const char *)arg2;
- (id)initWithRecordName:(const char *)arg1 type:(const char *)arg2 node:(id)arg3;
- (BOOL)isOpen;
- (id)name;
- (id)node;
- (BOOL)open;
- (BOOL)removeAttribute:(id)arg1;
- (BOOL)removeValue:(id)arg1 fromAttributeType:(id)arg2;
- (BOOL)removeValueID:(unsigned int)arg1 fromAttributeType:(id)arg2;
- (long long)setRecordNameTo:(id)arg1;
- (BOOL)setValue:(id)arg1 withValueID:(unsigned int)arg2 forAttributeType:(id)arg3;

@end

