//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSImage;

@interface ADMGuestUserConfig : NSObject
{
    NSImage *mDefaultGuestPicture;
}

+ (BOOL)_isFDEEnabled;
+ (long long)guestMode;
+ (BOOL)isGuestEnabled;
+ (void)setGuestEnabled:(BOOL)arg1;
+ (id)sharedConfig;
+ (void)syncGuestState;
- (id)_generateGuestPassword;
- (id)_imageFromCGImage1x:(struct CGImage *)arg1 andCGImage2x:(struct CGImage *)arg2;
- (id)createGuestAccount;
- (void)dealloc;
- (id)findGuestAccount;
- (id)guestUserPicture;
- (id)init;
- (BOOL)isGuestAccountEnabled;
- (void)setGuestAccountEnabled:(BOOL)arg1;

@end

