//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ADMInternetServices : NSObject
{
}

+ (id)sharedInternetServices;
- (struct __CFBundle *)_netFSServerFrameworkBundle;
- (BOOL)faxReceiveEnabled;
- (BOOL)ftpServerEnabled;
- (BOOL)httpdEnabled;
- (BOOL)isFTPServerAvailable;
- (BOOL)isFaxReceiveAvailable;
- (BOOL)isGuestForProtocolEnabled:(id)arg1;
- (BOOL)isHttpdAvailable;
- (BOOL)isNSCProtocolAvailable:(id)arg1;
- (BOOL)isNSCProtocolEnabled:(id)arg1;
- (BOOL)isNSServerShuttingDown:(id)arg1;
- (BOOL)isOpticalDiscSharingEnabled;
- (BOOL)isRemoteAEServerAvailable;
- (BOOL)isSSHServerAvailable;
- (void)nscServerCancelShutdown:(id)arg1 refNum:(unsigned int)arg2;
- (unsigned int)nscServerShutdown:(id)arg1 withDelay:(int)arg2;
- (long long)numberOfClientsForProtocols:(id)arg1;
- (BOOL)remoteAEServerEnabled;
- (void)saveNatPrefs:(id)arg1;
- (BOOL)screensharingEnabled;
- (void)sendSIGHUPToEfax;
- (void)setFTPServerEnabled:(BOOL)arg1;
- (void)setFaxReceiveEnabled:(BOOL)arg1;
- (void)setGuestForProtocol:(id)arg1 enabled:(BOOL)arg2;
- (void)setHttpdEnabled:(BOOL)arg1;
- (BOOL)setInetDServiceEnabled:(id)arg1 enabled:(BOOL)arg2;
- (void)setNSCProtocols:(id)arg1 enabled:(BOOL)arg2;
- (void)setOpticalDiscSharingEnabled:(BOOL)arg1;
- (void)setRemoteAEServerEnabled:(BOOL)arg1;
- (void)setSSHServerEnabled:(BOOL)arg1;
- (void)setScreensharingEnabled:(BOOL)arg1;
- (BOOL)sshServerEnabled;

@end

