//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdminAuthenticator.h"

@interface AdminDSAuthenticator : AdminAuthenticator
{
    BOOL _didClearTextAuthentication;
}

+ (id)sharedDSAuthenticator;
+ (id)sharedDSClearTextAuthenticator;
- (void)authenticateUsingAuthorization:(id)arg1;
- (void)authenticateUsingAuthorization:(id)arg1 userName:(id)arg2 password:(id)arg3;
- (BOOL)authenticateUsingAuthorizationSync:(id)arg1;
- (void)authenticateUsingAuthorizationSync:(id)arg1 userName:(id)arg2 password:(id)arg3;
- (void)dealloc;
- (void)deauthenticate;
@property(readonly) BOOL didClearTextAuthentication; // @synthesize didClearTextAuthentication=_didClearTextAuthentication;
- (void)finalize;

@end

