//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface AdminAuthenticator : NSObject
{
    BOOL _syncWaitDone;
    BOOL _wantsClearTextAuthentication;
}

+ (id)sharedAuthenticator;
+ (id)sharedClearTextAuthenticator;
- (void)_toolStartedNotification:(id)arg1;
- (void)authenticateUsingAuthorization:(id)arg1;
- (void)authenticateUsingAuthorization:(id)arg1 userName:(id)arg2 password:(id)arg3;
- (BOOL)authenticateUsingAuthorizationSync:(id)arg1;
- (void)authenticateUsingAuthorizationSync:(id)arg1 userName:(id)arg2 password:(id)arg3;
- (void)dealloc;
- (void)deauthenticate;
- (void)finalize;
- (id)init;
- (id)initClearTextAuthenticator;
- (BOOL)isAuthenticated;
@property(readonly) BOOL wantsClearTextAuthentication; // @synthesize wantsClearTextAuthentication=_wantsClearTextAuthentication;

@end

