//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface AdminDirectoryService : NSObject
{
    unsigned int mDirReference;
    NSString *mNameOfDefaultLocalNode;
    NSString *mNameOfSearchNode;
}

+ (unsigned int)dirReferenceForServiceAtAddress:(id)arg1 name:(id)arg2 password:(id)arg3 port:(long long)arg4;
+ (id)directoryServiceAtAddress:(id)arg1 name:(id)arg2 password:(id)arg3 port:(long long)arg4;
+ (id)sharedDirectoryService;
+ (unsigned int)sharedSession;
- (void)close;
- (void)dealloc;
- (void)finalize;
- (id)initWithDirectoryServiceAtAddress:(id)arg1 name:(id)arg2 password:(id)arg3 port:(long long)arg4;
- (BOOL)isOpen;
- (id)nameOfDefaultLocalNode;
- (id)nameOfNodeWithName:(CDStruct_7d936526 *)arg1 patternMatch:(int)arg2;
- (id)nameOfSearchNode;
- (id)namesOfNodeWithName:(CDStruct_7d936526 *)arg1 patternMatch:(int)arg2;
- (void)open;
- (unsigned int)session;

@end

