//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ADMLoginPrefs : NSObject
{
}

+ (id)sharedLoginPrefs;
- (BOOL)_boolFromCFValue:(void *)arg1;
- (struct __CFBundle *)_loginFrameworkBundle;
- (int)_setAutoLoginPassword:(id)arg1;
- (id)automaticLoginUser;
- (BOOL)disableRestartShutdown;
- (BOOL)isIMEnabled;
- (BOOL)isVOEnabled;
- (id)loginAuthenticator;
- (long long)numberOfRetriesBeforeHintIsDisplayed;
- (BOOL)otherUserEnabled;
- (void)setAutoLoginUser:(id)arg1 password:(id)arg2;
- (BOOL)setAutomaticLoginUser:(id)arg1 password:(id)arg2;
- (BOOL)setAutomaticLoginUser:(id)arg1 uid:(long long)arg2 password:(id)arg3;
- (void)setDisableRestartShutdown:(BOOL)arg1;
- (void)setGuestUserPassword:(id)arg1 accountName:(id)arg2;
- (void)setIMEnabled:(BOOL)arg1;
- (void)setLoginAuthenticator:(id)arg1;
- (void)setNumberOfRetriesBeforeHintIsDisplayed:(long long)arg1;
- (void)setShowHostname:(BOOL)arg1;
- (void)setVOEnabled:(BOOL)arg1;
- (BOOL)showHostname;
- (void)showList:(BOOL)arg1;
- (BOOL)showListEnabled;
- (void)showOtherUser:(BOOL)arg1;
- (void)syncLoginPrefs;

@end

