//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ADMNetworkTimeClient : NSObject
{
}

+ (id)sharedNetworkTimeClient;
- (BOOL)isRunning;
- (BOOL)isServing;
- (BOOL)isSyncing;
- (void)restart;
- (void)restartAsync;
- (id)server;
- (id)servers;
- (void)setLaunchAtStartup:(BOOL)arg1;
- (void)setServer:(id)arg1;
- (void)setServers:(id)arg1;
- (void)start;
- (void)startSyncing;
- (void)startWithAuthorization:(struct AuthorizationOpaqueRef *)arg1;
- (void)stop;
- (void)stopSyncing;
- (void)stopWithAuthorization:(struct AuthorizationOpaqueRef *)arg1;
- (BOOL)synchronizeNow;

@end

