//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface ADMNetworkTimeServer : NSObject
{
    NSString *_descriptiveName;
    NSString *_address;
}

+ (id)serverWithConfigurationString:(id)arg1;
- (id)address;
- (id)configurationString;
- (void)dealloc;
- (id)description;
- (id)descriptiveName;
- (id)initWithConfigurationString:(id)arg1;
- (void)setAddress:(id)arg1;
- (void)setDescriptiveName:(id)arg1;

@end

