//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ADMPrinterSharingConfig : NSObject
{
}

+ (id)sharedPrinterSharing;
- (BOOL)canSeeNetworkPrinters;
- (BOOL)isPrinterSharingOn;
- (void)setCanSeeNetworkPrinters:(BOOL)arg1;
- (void)setPrinterSharingEnabled:(BOOL)arg1;

@end

