//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface ADMUserAccountUtilities : NSObject
{
}

+ (int)changeKeychainPassword:(id)arg1 oldPassword:(id)arg2;
+ (id)changePasswordForUser:(id)arg1 oldPassword:(id)arg2 newPassword:(id)arg3;
+ (id)changePasswordForUser:(id)arg1 oldPassword:(id)arg2 newPassword:(id)arg3 cdpCompletionHandler:(CDUnknownBlockType)arg4;
+ (id)humanSizeForSize:(unsigned long long)arg1;
+ (void)killProcessesForUserID:(unsigned int)arg1;
+ (id)listOfProcessOwners;
+ (long long)numberForKey:(struct __CFString *)arg1 fromCFDict:(struct __CFDictionary *)arg2;
+ (id)passwordErrorStringForODError:(long long)arg1;

@end

