//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSString;

@interface ADMWebServerConfig : NSObject
{
    NSString *_configurationDirectory;
}

+ (id)sharedRemoteAdminServerConfig;
+ (id)sharedWebServerConfig;
- (void)dealloc;
- (id)initWithConfigurationDirectory:(id)arg1;
- (BOOL)isValidServerName:(id)arg1;
- (BOOL)isWebServerRunning;
- (void)restartWebServer;
- (void)startWebServer;
- (void)stopWebServer;
- (id)webServerName;

@end

