//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class NSData, NSXPCConnection, SFAuthorization, WriteConfigOnewayMessageDispatcher;

@interface WriteConfigClient : NSObject
{
    SFAuthorization *_authorization;
    NSXPCConnection *_connection;
    WriteConfigOnewayMessageDispatcher *_onewayMessageDispatcher;
}

+ (id)sharedClient;
- (void)_connectionDidInvalidate;
- (void)addBarrierBlock:(CDUnknownBlockType)arg1;
- (void)authenticateUsingAuthorization:(id)arg1;
- (BOOL)authenticateUsingAuthorizationSync:(id)arg1;
@property(readonly) SFAuthorization *authorization; // @synthesize authorization=_authorization;
@property(readonly) NSData *authorizationData; // @dynamic authorizationData;
@property(readonly) NSXPCConnection *connection; // @synthesize connection=_connection;
- (void)dealloc;
- (void)disconnect;
- (BOOL)isAuthenticated;
@property(readonly) id <XPCWriteConfigOneway> remoteProxy; // @dynamic remoteProxy;
- (void)runBlockSync:(CDUnknownBlockType)arg1;
- (BOOL)runBlockSync:(CDUnknownBlockType)arg1 timeOut:(unsigned long long)arg2;
- (id)syncProxyWithSemaphore:(id)arg1;

@end

